import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";   // 👈 add this
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '../styles/prism-coldark-theme.css';
import { AppContextProvider } from "../context/AppContext.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>   {/* ✅ Wrap your entire app in ClerkProvider */}
      <AppContextProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
      </AppContextProvider>
    </ClerkProvider>
  );
}
